name: Main_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      
    - run: npm install
      working-directory: /Hahn.ApplicatonProcess.December2020.UI
      
    - run: npm run-script build
      working-directory: /Hahn.ApplicatonProcess.December2020.UI
